export interface Card {
  set: string;
  number: number;
  name: string;
  type: string;
  rarity: string;
}

export const CARDS: Card[] = [
  { set: "A1", number: 1, name: "Bulbasaur", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 2, name: "Ivysaur", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1", number: 3, name: "Venusaur", type: "G Stage 2", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 4,
    name: "Venusaur ex",
    type: "G Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 5, name: "Caterpie", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 6, name: "Metapod", type: "G Stage 1", rarity: "◊" },
  {
    set: "A1",
    number: 7,
    name: "Butterfree",
    type: "G Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 8, name: "Weedle", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 9, name: "Kakuna", type: "G Stage 1", rarity: "◊" },
  { set: "A1", number: 10, name: "Beedrill", type: "G Stage 2", rarity: "◊◊◊" },
  { set: "A1", number: 11, name: "Oddish", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 12, name: "Gloom", type: "G Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 13,
    name: "Vileplume",
    type: "G Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 14, name: "Paras", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 15, name: "Parasect", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1", number: 16, name: "Venonat", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 17, name: "Venomoth", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1", number: 18, name: "Bellsprout", type: "G Basic", rarity: "◊" },
  {
    set: "A1",
    number: 19,
    name: "Weepinbell",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A1",
    number: 20,
    name: "Victreebel",
    type: "G Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 21, name: "Exeggcute", type: "G Basic", rarity: "◊" },
  {
    set: "A1",
    number: 22,
    name: "Exeggutor",
    type: "G Stage 1",
    rarity: "◊◊◊",
  },
  {
    set: "A1",
    number: 23,
    name: "Exeggutor ex",
    type: "G Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 24, name: "Tangela", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 25, name: "Scyther", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 26, name: "Pinsir", type: "G Basic", rarity: "◊◊" },
  { set: "A1", number: 27, name: "Cottonee", type: "G Basic", rarity: "◊" },
  {
    set: "A1",
    number: 28,
    name: "Whimsicott",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 29, name: "Petilil", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 30, name: "Lilligant", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1", number: 31, name: "Skiddo", type: "G Basic", rarity: "◊" },
  { set: "A1", number: 32, name: "Gogoat", type: "G Stage 1", rarity: "◊" },
  { set: "A1", number: 33, name: "Charmander", type: "R Basic", rarity: "◊" },
  {
    set: "A1",
    number: 34,
    name: "Charmeleon",
    type: "R Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A1",
    number: 35,
    name: "Charizard",
    type: "R Stage 2",
    rarity: "◊◊◊",
  },
  {
    set: "A1",
    number: 36,
    name: "Charizard ex",
    type: "R Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 37, name: "Vulpix", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 38, name: "Ninetales", type: "R Stage 1", rarity: "◊◊" },
  { set: "A1", number: 39, name: "Growlithe", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 40, name: "Arcanine", type: "R Stage 1", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 41,
    name: "Arcanine ex",
    type: "R Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 42, name: "Ponyta", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 43, name: "Rapidash", type: "R Stage 1", rarity: "◊◊" },
  { set: "A1", number: 44, name: "Magmar", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 45, name: "Flareon", type: "R Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 46, name: "Moltres", type: "R Basic", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 47,
    name: "Moltres ex",
    type: "R Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 48, name: "Heatmor", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 49, name: "Salandit", type: "R Basic", rarity: "◊" },
  { set: "A1", number: 50, name: "Salazzle", type: "R Stage 1", rarity: "◊" },
  { set: "A1", number: 51, name: "Sizzlipede", type: "R Basic", rarity: "◊" },
  {
    set: "A1",
    number: 52,
    name: "Centiskorch",
    type: "R Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 53, name: "Squirtle", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 54, name: "Wartortle", type: "W Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 55,
    name: "Blastoise",
    type: "W Stage 2",
    rarity: "◊◊◊",
  },
  {
    set: "A1",
    number: 56,
    name: "Blastoise ex",
    type: "W Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 57, name: "Psyduck", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 58, name: "Golduck", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 59, name: "Poliwag", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 60, name: "Poliwhirl", type: "W Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 61,
    name: "Poliwrath",
    type: "W Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 62, name: "Tentacool", type: "W Basic", rarity: "◊" },
  {
    set: "A1",
    number: 63,
    name: "Tentacruel",
    type: "W Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 64, name: "Seel", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 65, name: "Dewgong", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 66, name: "Shellder", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 67, name: "Cloyster", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 68, name: "Krabby", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 69, name: "Kingler", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 70, name: "Horsea", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 71, name: "Seadra", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 72, name: "Goldeen", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 73, name: "Seaking", type: "W Stage 1", rarity: "◊" },
  { set: "A1", number: 74, name: "Staryu", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 75, name: "Starmie", type: "W Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 76,
    name: "Starmie ex",
    type: "W Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 77, name: "Magikarp", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 78, name: "Gyarados", type: "W Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 79, name: "Lapras", type: "W Basic", rarity: "◊◊◊" },
  { set: "A1", number: 80, name: "Vaporeon", type: "W Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 81, name: "Omanyte", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 82, name: "Omastar", type: "W Stage 2", rarity: "◊◊◊" },
  { set: "A1", number: 83, name: "Articuno", type: "W Basic", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 84,
    name: "Articuno ex",
    type: "W Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 85, name: "Ducklett", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 86, name: "Swanna", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 87, name: "Froakie", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 88, name: "Frogadier", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 89, name: "Greninja", type: "W Stage 2", rarity: "◊◊◊" },
  { set: "A1", number: 90, name: "Pyukumuku", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 91, name: "Bruxish", type: "W Basic", rarity: "◊◊" },
  { set: "A1", number: 92, name: "Snom", type: "W Basic", rarity: "◊" },
  { set: "A1", number: 93, name: "Frosmoth", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1", number: 94, name: "Pikachu", type: "L Basic", rarity: "◊" },
  { set: "A1", number: 95, name: "Raichu", type: "L Stage 1", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 96,
    name: "Pikachu ex",
    type: "L Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 97, name: "Magnemite", type: "L Basic", rarity: "◊" },
  { set: "A1", number: 98, name: "Magneton", type: "L Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 99, name: "Voltorb", type: "L Basic", rarity: "◊" },
  {
    set: "A1",
    number: 100,
    name: "Electrode",
    type: "L Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 101, name: "Electabuzz", type: "L Basic", rarity: "◊" },
  { set: "A1", number: 102, name: "Jolteon", type: "L Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 103, name: "Zapdos", type: "L Basic", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 104,
    name: "Zapdos ex",
    type: "L Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 105, name: "Blitzle", type: "L Basic", rarity: "◊" },
  {
    set: "A1",
    number: 106,
    name: "Zebstrika",
    type: "L Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 107, name: "Tynamo", type: "L Basic", rarity: "◊" },
  {
    set: "A1",
    number: 108,
    name: "Eelektrik",
    type: "L Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A1",
    number: 109,
    name: "Eelektross",
    type: "L Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 110, name: "Helioptile", type: "L Basic", rarity: "◊" },
  { set: "A1", number: 111, name: "Heliolisk", type: "L Stage 1", rarity: "◊" },
  { set: "A1", number: 112, name: "Pincurchin", type: "L Basic", rarity: "◊◊" },
  { set: "A1", number: 113, name: "Clefairy", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 114, name: "Clefable", type: "P Stage 1", rarity: "◊◊" },
  { set: "A1", number: 115, name: "Abra", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 116, name: "Kadabra", type: "P Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 117,
    name: "Alakazam",
    type: "P Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 118, name: "Slowpoke", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 119, name: "Slowbro", type: "P Stage 1", rarity: "◊◊" },
  { set: "A1", number: 120, name: "Gastly", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 121, name: "Haunter", type: "P Stage 1", rarity: "◊◊" },
  { set: "A1", number: 122, name: "Gengar", type: "P Stage 2", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 123,
    name: "Gengar ex",
    type: "P Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 124, name: "Drowzee", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 125, name: "Hypno", type: "P Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 126, name: "Mr. Mime", type: "P Basic", rarity: "◊◊" },
  { set: "A1", number: 127, name: "Jynx", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 128, name: "Mewtwo", type: "P Basic", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 129,
    name: "Mewtwo ex",
    type: "P Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 130, name: "Ralts", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 131, name: "Kirlia", type: "P Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 132,
    name: "Gardevoir",
    type: "P Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 133, name: "Woobat", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 134, name: "Swoobat", type: "P Stage 1", rarity: "◊" },
  { set: "A1", number: 135, name: "Golett", type: "P Basic", rarity: "◊" },
  { set: "A1", number: 136, name: "Golurk", type: "P Stage 1", rarity: "◊◊" },
  { set: "A1", number: 137, name: "Sandshrew", type: "F Basic", rarity: "◊" },
  {
    set: "A1",
    number: 138,
    name: "Sandslash",
    type: "F Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 139, name: "Diglett", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 140, name: "Dugtrio", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 141, name: "Mankey", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 142, name: "Primeape", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 143, name: "Machop", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 144, name: "Machoke", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 145, name: "Machamp", type: "F Stage 2", rarity: "◊◊◊" },
  {
    set: "A1",
    number: 146,
    name: "Machamp ex",
    type: "F Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 147, name: "Geodude", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 148, name: "Graveler", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 149, name: "Golem", type: "F Stage 2", rarity: "◊◊◊" },
  { set: "A1", number: 150, name: "Onix", type: "F Basic", rarity: "◊◊" },
  { set: "A1", number: 151, name: "Cubone", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 152, name: "Marowak", type: "F Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 153,
    name: "Marowak ex",
    type: "F Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 154, name: "Hitmonlee", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 155, name: "Hitmonchan", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 156, name: "Rhyhorn", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 157, name: "Rhydon", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 158, name: "Kabuto", type: "F Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 159,
    name: "Kabutops",
    type: "F Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 160, name: "Mienfoo", type: "F Basic", rarity: "◊" },
  { set: "A1", number: 161, name: "Mienshao", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1", number: 162, name: "Clobbopus", type: "F Basic", rarity: "◊" },
  {
    set: "A1",
    number: 163,
    name: "Grapploct",
    type: "F Stage 1",
    rarity: "◊◊",
  },
  { set: "A1", number: 164, name: "Ekans", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 165, name: "Arbok", type: "D Stage 1", rarity: "◊◊" },
  { set: "A1", number: 166, name: "Nidoran♀", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 167, name: "Nidorina", type: "D Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 168,
    name: "Nidoqueen",
    type: "D Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 169, name: "Nidoran♂", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 170, name: "Nidorino", type: "D Stage 1", rarity: "◊◊" },
  {
    set: "A1",
    number: 171,
    name: "Nidoking",
    type: "D Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 172, name: "Zubat", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 173, name: "Golbat", type: "D Stage 1", rarity: "◊◊" },
  { set: "A1", number: 174, name: "Grimer", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 175, name: "Muk", type: "D Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 176, name: "Koffing", type: "D Basic", rarity: "◊" },
  { set: "A1", number: 177, name: "Weezing", type: "D Stage 1", rarity: "◊◊◊" },
  { set: "A1", number: 178, name: "Mawile", type: "M Basic", rarity: "◊" },
  { set: "A1", number: 179, name: "Pawniard", type: "M Basic", rarity: "◊" },
  { set: "A1", number: 180, name: "Bisharp", type: "M Stage 1", rarity: "◊◊" },
  { set: "A1", number: 181, name: "Meltan", type: "M Basic", rarity: "◊" },
  {
    set: "A1",
    number: 182,
    name: "Melmetal",
    type: "M Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 183, name: "Dratini", type: "N Basic", rarity: "◊" },
  {
    set: "A1",
    number: 184,
    name: "Dragonair",
    type: "N Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A1",
    number: 185,
    name: "Dragonite",
    type: "N Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 186, name: "Pidgey", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 187, name: "Pidgeotto", type: "C Stage 1", rarity: "◊" },
  { set: "A1", number: 188, name: "Pidgeot", type: "C Stage 2", rarity: "◊◊◊" },
  { set: "A1", number: 189, name: "Rattata", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 190, name: "Raticate", type: "C Stage 1", rarity: "◊" },
  { set: "A1", number: 191, name: "Spearow", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 192, name: "Fearow", type: "C Stage 1", rarity: "◊" },
  { set: "A1", number: 193, name: "Jigglypuff", type: "C Basic", rarity: "◊" },
  {
    set: "A1",
    number: 194,
    name: "Wigglytuff",
    type: "C Stage 1",
    rarity: "◊",
  },
  {
    set: "A1",
    number: 195,
    name: "Wigglytuff ex",
    type: "C Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1", number: 196, name: "Meowth", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 197, name: "Persian", type: "C Stage 1", rarity: "◊◊" },
  { set: "A1", number: 198, name: "Farfetch'd", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 199, name: "Doduo", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 200, name: "Dodrio", type: "C Stage 1", rarity: "◊◊" },
  { set: "A1", number: 201, name: "Lickitung", type: "C Basic", rarity: "◊◊" },
  { set: "A1", number: 202, name: "Chansey", type: "C Basic", rarity: "◊◊" },
  {
    set: "A1",
    number: 203,
    name: "Kangaskhan",
    type: "C Basic",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 204, name: "Tauros", type: "C Basic", rarity: "◊◊" },
  { set: "A1", number: 205, name: "Ditto", type: "C Basic", rarity: "◊◊◊" },
  { set: "A1", number: 206, name: "Eevee", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 207, name: "Eevee", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 208, name: "Eevee", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 209, name: "Porygon", type: "C Basic", rarity: "◊◊" },
  {
    set: "A1",
    number: 210,
    name: "Aerodactyl",
    type: "C Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A1", number: 211, name: "Snorlax", type: "C Basic", rarity: "◊◊◊" },
  { set: "A1", number: 212, name: "Minccino", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 213, name: "Cinccino", type: "C Stage 1", rarity: "◊◊" },
  { set: "A1", number: 214, name: "Wooloo", type: "C Basic", rarity: "◊" },
  { set: "A1", number: 215, name: "Dubwool", type: "C Stage 1", rarity: "◊" },
  { set: "A1", number: 216, name: "Helix Fossil", type: "Item", rarity: "◊" },
  { set: "A1", number: 217, name: "Dome Fossil", type: "Item", rarity: "◊" },
  { set: "A1", number: 218, name: "Old Amber", type: "Item", rarity: "◊" },
  { set: "A1", number: 219, name: "Erika", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 220, name: "Misty", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 221, name: "Blaine", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 222, name: "Koga", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 223, name: "Giovanni", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 224, name: "Brock", type: "Supporter", rarity: "◊◊" },
  { set: "A1", number: 225, name: "Sabrina", type: "Supporter", rarity: "◊◊" },
  {
    set: "A1",
    number: 226,
    name: "Lt. Surge",
    type: "Supporter",
    rarity: "◊◊",
  },
  { set: "A1", number: 227, name: "Bulbasaur", type: "G Basic", rarity: "☆" },
  { set: "A1", number: 228, name: "Gloom", type: "G Stage 1", rarity: "☆" },
  { set: "A1", number: 229, name: "Pinsir", type: "G Basic", rarity: "☆" },
  { set: "A1", number: 230, name: "Charmander", type: "R Basic", rarity: "☆" },
  { set: "A1", number: 231, name: "Rapidash", type: "R Stage 1", rarity: "☆" },
  { set: "A1", number: 232, name: "Squirtle", type: "W Basic", rarity: "☆" },
  { set: "A1", number: 233, name: "Gyarados", type: "W Stage 1", rarity: "☆" },
  { set: "A1", number: 234, name: "Lapras", type: "W Basic", rarity: "☆" },
  { set: "A1", number: 235, name: "Electrode", type: "L Stage 1", rarity: "☆" },
  { set: "A1", number: 236, name: "Alakazam", type: "P Stage 2", rarity: "☆" },
  { set: "A1", number: 237, name: "Slowpoke", type: "P Basic", rarity: "☆" },
  { set: "A1", number: 238, name: "Diglett", type: "F Basic", rarity: "☆" },
  { set: "A1", number: 239, name: "Cubone", type: "F Basic", rarity: "☆" },
  { set: "A1", number: 240, name: "Nidoqueen", type: "D Stage 2", rarity: "☆" },
  { set: "A1", number: 241, name: "Nidoking", type: "D Stage 2", rarity: "☆" },
  { set: "A1", number: 242, name: "Golbat", type: "D Stage 1", rarity: "☆" },
  { set: "A1", number: 243, name: "Weezing", type: "D Stage 1", rarity: "☆" },
  { set: "A1", number: 244, name: "Dragonite", type: "N Stage 2", rarity: "☆" },
  { set: "A1", number: 245, name: "Pidgeot", type: "C Stage 2", rarity: "☆" },
  { set: "A1", number: 246, name: "Meowth", type: "C Basic", rarity: "☆" },
  { set: "A1", number: 247, name: "Ditto", type: "C Basic", rarity: "☆" },
  { set: "A1", number: 248, name: "Eevee", type: "C Basic", rarity: "☆" },
  { set: "A1", number: 249, name: "Porygon", type: "C Basic", rarity: "☆" },
  { set: "A1", number: 250, name: "Snorlax", type: "C Basic", rarity: "☆" },
  {
    set: "A1",
    number: 251,
    name: "Venusaur ex",
    type: "G Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 252,
    name: "Exeggutor ex",
    type: "G Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 253,
    name: "Charizard ex",
    type: "R Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 254,
    name: "Arcanine ex",
    type: "R Stage 1",
    rarity: "☆☆",
  },
  { set: "A1", number: 255, name: "Moltres ex", type: "R Basic", rarity: "☆☆" },
  {
    set: "A1",
    number: 256,
    name: "Blastoise ex",
    type: "W Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 257,
    name: "Starmie ex",
    type: "W Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 258,
    name: "Articuno ex",
    type: "W Basic",
    rarity: "☆☆",
  },
  { set: "A1", number: 259, name: "Pikachu ex", type: "L Basic", rarity: "☆☆" },
  { set: "A1", number: 260, name: "Zapdos ex", type: "L Basic", rarity: "☆☆" },
  {
    set: "A1",
    number: 261,
    name: "Gengar ex",
    type: "P Stage 2",
    rarity: "☆☆",
  },
  { set: "A1", number: 262, name: "Mewtwo ex", type: "P Basic", rarity: "☆☆" },
  {
    set: "A1",
    number: 263,
    name: "Machamp ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 264,
    name: "Marowak ex",
    type: "F Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 265,
    name: "Wigglytuff ex",
    type: "C Stage 1",
    rarity: "☆☆",
  },
  { set: "A1", number: 266, name: "Erika", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 267, name: "Misty", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 268, name: "Blaine", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 269, name: "Koga", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 270, name: "Giovanni", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 271, name: "Brock", type: "Supporter", rarity: "☆☆" },
  { set: "A1", number: 272, name: "Sabrina", type: "Supporter", rarity: "☆☆" },
  {
    set: "A1",
    number: 273,
    name: "Lt. Surge",
    type: "Supporter",
    rarity: "☆☆",
  },
  { set: "A1", number: 274, name: "Moltres ex", type: "R Basic", rarity: "☆☆" },
  {
    set: "A1",
    number: 275,
    name: "Articuno ex",
    type: "W Basic",
    rarity: "☆☆",
  },
  { set: "A1", number: 276, name: "Zapdos ex", type: "L Basic", rarity: "☆☆" },
  {
    set: "A1",
    number: 277,
    name: "Gengar ex",
    type: "P Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 278,
    name: "Machamp ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 279,
    name: "Wigglytuff ex",
    type: "C Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A1",
    number: 280,
    name: "Charizard ex",
    type: "R Stage 2",
    rarity: "☆☆☆",
  },
  {
    set: "A1",
    number: 281,
    name: "Pikachu ex",
    type: "L Basic",
    rarity: "☆☆☆",
  },
  { set: "A1", number: 282, name: "Mewtwo ex", type: "P Basic", rarity: "☆☆☆" },
  { set: "A1", number: 283, name: "Mew", type: "P Basic", rarity: "☆☆☆" },
  {
    set: "A1",
    number: 284,
    name: "Charizard ex",
    type: "R Stage 2",
    rarity: "Crown Rare",
  },
  {
    set: "A1",
    number: 285,
    name: "Pikachu ex",
    type: "L Basic",
    rarity: "Crown Rare",
  },
  {
    set: "A1",
    number: 286,
    name: "Mewtwo ex",
    type: "P Basic",
    rarity: "Crown Rare",
  },
  { set: "A1a", number: 1, name: "Exeggcute", type: "G Basic", rarity: "◊" },
  { set: "A1a", number: 2, name: "Exeggutor", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 3, name: "Celebi ex", type: "G Basic", rarity: "◊◊◊◊" },
  { set: "A1a", number: 4, name: "Snivy", type: "G Basic", rarity: "◊" },
  { set: "A1a", number: 5, name: "Servine", type: "G Stage 1", rarity: "◊◊" },
  {
    set: "A1a",
    number: 6,
    name: "Serperior",
    type: "G Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A1a", number: 7, name: "Morelull", type: "G Basic", rarity: "◊" },
  { set: "A1a", number: 8, name: "Shiinotic", type: "G Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 9, name: "Dhelmise", type: "G Basic", rarity: "◊◊" },
  { set: "A1a", number: 10, name: "Ponyta", type: "R Basic", rarity: "◊" },
  { set: "A1a", number: 11, name: "Rapidash", type: "R Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 12, name: "Magmar", type: "R Basic", rarity: "◊◊" },
  { set: "A1a", number: 13, name: "Larvesta", type: "R Basic", rarity: "◊" },
  {
    set: "A1a",
    number: 14,
    name: "Volcarona",
    type: "R Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A1a", number: 15, name: "Salandit", type: "R Basic", rarity: "◊" },
  { set: "A1a", number: 16, name: "Salazzle", type: "R Stage 1", rarity: "◊" },
  { set: "A1a", number: 17, name: "Magikarp", type: "W Basic", rarity: "◊" },
  {
    set: "A1a",
    number: 18,
    name: "Gyarados ex",
    type: "W Stage 1",
    rarity: "◊◊◊◊",
  },
  {
    set: "A1a",
    number: 19,
    name: "Vaporeon",
    type: "W Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A1a", number: 20, name: "Finneon", type: "W Basic", rarity: "◊" },
  { set: "A1a", number: 21, name: "Lumineon", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 22, name: "Chewtle", type: "W Basic", rarity: "◊" },
  { set: "A1a", number: 23, name: "Drednaw", type: "W Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 24, name: "Cramorant", type: "W Basic", rarity: "◊" },
  { set: "A1a", number: 25, name: "Pikachu", type: "L Basic", rarity: "◊" },
  { set: "A1a", number: 26, name: "Raichu", type: "L Stage 1", rarity: "◊◊◊" },
  { set: "A1a", number: 27, name: "Electabuzz", type: "L Basic", rarity: "◊◊" },
  { set: "A1a", number: 28, name: "Joltik", type: "L Basic", rarity: "◊" },
  {
    set: "A1a",
    number: 29,
    name: "Galvantula",
    type: "L Stage 1",
    rarity: "◊◊",
  },
  { set: "A1a", number: 30, name: "Dedenne", type: "L Basic", rarity: "◊" },
  { set: "A1a", number: 31, name: "Mew", type: "P Basic", rarity: "◊◊◊" },
  { set: "A1a", number: 32, name: "Mew ex", type: "P Basic", rarity: "◊◊◊◊" },
  { set: "A1a", number: 33, name: "Sigilyph", type: "P Basic", rarity: "◊◊" },
  { set: "A1a", number: 34, name: "Elgyem", type: "P Basic", rarity: "◊" },
  { set: "A1a", number: 35, name: "Beheeyem", type: "P Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 36, name: "Flabébé", type: "P Basic", rarity: "◊" },
  { set: "A1a", number: 37, name: "Floette", type: "P Stage 1", rarity: "◊" },
  { set: "A1a", number: 38, name: "Florges", type: "P Stage 2", rarity: "◊◊" },
  { set: "A1a", number: 39, name: "Swirlix", type: "P Basic", rarity: "◊" },
  { set: "A1a", number: 40, name: "Slurpuff", type: "P Stage 1", rarity: "◊" },
  { set: "A1a", number: 41, name: "Mankey", type: "F Basic", rarity: "◊" },
  { set: "A1a", number: 42, name: "Primeape", type: "F Stage 1", rarity: "◊" },
  { set: "A1a", number: 43, name: "Geodude", type: "F Basic", rarity: "◊" },
  { set: "A1a", number: 44, name: "Graveler", type: "F Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 45, name: "Golem", type: "F Stage 2", rarity: "◊◊◊" },
  {
    set: "A1a",
    number: 46,
    name: "Aerodactyl ex",
    type: "F Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A1a", number: 47, name: "Marshadow", type: "F Basic", rarity: "◊◊◊" },
  {
    set: "A1a",
    number: 48,
    name: "Stonjourner",
    type: "F Basic",
    rarity: "◊◊",
  },
  { set: "A1a", number: 49, name: "Koffing", type: "D Basic", rarity: "◊" },
  { set: "A1a", number: 50, name: "Weezing", type: "D Stage 1", rarity: "◊◊" },
  { set: "A1a", number: 51, name: "Purrloin", type: "D Basic", rarity: "◊" },
  { set: "A1a", number: 52, name: "Liepard", type: "D Stage 1", rarity: "◊" },
  { set: "A1a", number: 53, name: "Venipede", type: "D Basic", rarity: "◊" },
  {
    set: "A1a",
    number: 54,
    name: "Whirlipede",
    type: "D Stage 1",
    rarity: "◊",
  },
  {
    set: "A1a",
    number: 55,
    name: "Scolipede",
    type: "D Stage 2",
    rarity: "◊◊",
  },
  { set: "A1a", number: 56, name: "Druddigon", type: "N Basic", rarity: "◊◊" },
  { set: "A1a", number: 57, name: "Pidgey", type: "C Basic", rarity: "◊" },
  { set: "A1a", number: 58, name: "Pidgeotto", type: "C Stage 1", rarity: "◊" },
  {
    set: "A1a",
    number: 59,
    name: "Pidgeot ex",
    type: "C Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A1a", number: 60, name: "Tauros", type: "C Basic", rarity: "◊◊◊" },
  { set: "A1a", number: 61, name: "Eevee", type: "C Basic", rarity: "◊" },
  { set: "A1a", number: 62, name: "Chatot", type: "C Basic", rarity: "◊" },
  { set: "A1a", number: 63, name: "Old Amber", type: "Item", rarity: "◊" },
  { set: "A1a", number: 64, name: "Pokémon Flute", type: "Item", rarity: "◊◊" },
  { set: "A1a", number: 65, name: "Mythical Slab", type: "Item", rarity: "◊◊" },
  {
    set: "A1a",
    number: 66,
    name: "Budding Expeditioner",
    type: "Supporter",
    rarity: "◊◊",
  },
  { set: "A1a", number: 67, name: "Blue", type: "Supporter", rarity: "◊◊" },
  { set: "A1a", number: 68, name: "Leaf", type: "Supporter", rarity: "◊◊" },
  { set: "A1a", number: 69, name: "Exeggutor", type: "G Stage 1", rarity: "☆" },
  { set: "A1a", number: 70, name: "Serperior", type: "G Stage 2", rarity: "☆" },
  { set: "A1a", number: 71, name: "Salandit", type: "R Basic", rarity: "☆" },
  { set: "A1a", number: 72, name: "Vaporeon", type: "W Stage 1", rarity: "☆" },
  { set: "A1a", number: 73, name: "Dedenne", type: "L Basic", rarity: "☆" },
  { set: "A1a", number: 74, name: "Marshadow", type: "F Basic", rarity: "☆" },
  { set: "A1a", number: 75, name: "Celebi ex", type: "G Basic", rarity: "☆☆" },
  {
    set: "A1a",
    number: 76,
    name: "Gyarados ex",
    type: "W Stage 1",
    rarity: "☆☆",
  },
  { set: "A1a", number: 77, name: "Mew ex", type: "P Basic", rarity: "☆☆" },
  {
    set: "A1a",
    number: 78,
    name: "Aerodactyl ex",
    type: "F Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A1a",
    number: 79,
    name: "Pidgeot ex",
    type: "C Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A1a",
    number: 80,
    name: "Budding Expeditioner",
    type: "Supporter",
    rarity: "☆☆",
  },
  { set: "A1a", number: 81, name: "Blue", type: "Supporter", rarity: "☆☆" },
  { set: "A1a", number: 82, name: "Leaf", type: "Supporter", rarity: "☆☆" },
  { set: "A1a", number: 83, name: "Mew ex", type: "P Basic", rarity: "☆☆" },
  {
    set: "A1a",
    number: 84,
    name: "Aerodactyl ex",
    type: "F Stage 1",
    rarity: "☆☆",
  },
  { set: "A1a", number: 85, name: "Celebi ex", type: "G Basic", rarity: "☆☆☆" },
  {
    set: "A1a",
    number: 86,
    name: "Mew ex",
    type: "P Basic",
    rarity: "Crown Rare",
  },
  { set: "A2", number: 1, name: "Oddish", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 2, name: "Gloom", type: "G Stage 1", rarity: "◊" },
  { set: "A2", number: 3, name: "Bellossom", type: "G Stage 2", rarity: "◊◊" },
  { set: "A2", number: 4, name: "Tangela", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 5, name: "Tangrowth", type: "G Stage 1", rarity: "◊◊" },
  { set: "A2", number: 6, name: "Yanma", type: "G Basic", rarity: "◊" },
  {
    set: "A2",
    number: 7,
    name: "Yanmega ex",
    type: "G Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 8, name: "Roselia", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 9, name: "Roserade", type: "G Stage 1", rarity: "◊◊" },
  { set: "A2", number: 10, name: "Turtwig", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 11, name: "Grotle", type: "G Stage 1", rarity: "◊◊" },
  { set: "A2", number: 12, name: "Torterra", type: "G Stage 2", rarity: "◊◊◊" },
  { set: "A2", number: 13, name: "Kricketot", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 14, name: "Kricketune", type: "G Stage 1", rarity: "◊" },
  { set: "A2", number: 15, name: "Burmy", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 16, name: "Wormadam", type: "G Stage 1", rarity: "◊" },
  { set: "A2", number: 17, name: "Combee", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 18, name: "Vespiquen", type: "G Stage 1", rarity: "◊◊" },
  { set: "A2", number: 19, name: "Carnivine", type: "G Basic", rarity: "◊◊" },
  { set: "A2", number: 20, name: "Leafeon", type: "G Stage 1", rarity: "◊◊◊" },
  { set: "A2", number: 21, name: "Mow Rotom", type: "G Basic", rarity: "◊" },
  { set: "A2", number: 22, name: "Shaymin", type: "G Basic", rarity: "◊◊◊" },
  { set: "A2", number: 23, name: "Magmar", type: "R Basic", rarity: "◊" },
  {
    set: "A2",
    number: 24,
    name: "Magmortar",
    type: "R Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 25, name: "Slugma", type: "R Basic", rarity: "◊" },
  { set: "A2", number: 26, name: "Magcargo", type: "R Stage 1", rarity: "◊◊" },
  { set: "A2", number: 27, name: "Chimchar", type: "R Basic", rarity: "◊" },
  { set: "A2", number: 28, name: "Monferno", type: "R Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 29,
    name: "Infernape ex",
    type: "R Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 30, name: "Heat Rotom", type: "R Basic", rarity: "◊" },
  { set: "A2", number: 31, name: "Swinub", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 32, name: "Piloswine", type: "W Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 33,
    name: "Mamoswine",
    type: "W Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 34, name: "Regice", type: "W Basic", rarity: "◊◊" },
  { set: "A2", number: 35, name: "Piplup", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 36, name: "Prinplup", type: "W Stage 1", rarity: "◊◊" },
  { set: "A2", number: 37, name: "Empoleon", type: "W Stage 2", rarity: "◊◊◊" },
  { set: "A2", number: 38, name: "Buizel", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 39, name: "Floatzel", type: "W Stage 1", rarity: "◊◊" },
  { set: "A2", number: 40, name: "Shellos", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 41, name: "Gastrodon", type: "W Stage 1", rarity: "◊◊" },
  { set: "A2", number: 42, name: "Finneon", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 43, name: "Lumineon", type: "W Stage 1", rarity: "◊◊" },
  { set: "A2", number: 44, name: "Snover", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 45, name: "Abomasnow", type: "W Stage 1", rarity: "◊◊" },
  { set: "A2", number: 46, name: "Glaceon", type: "W Stage 1", rarity: "◊◊◊" },
  { set: "A2", number: 47, name: "Wash Rotom", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 48, name: "Frost Rotom", type: "W Basic", rarity: "◊" },
  { set: "A2", number: 49, name: "Palkia ex", type: "W Basic", rarity: "◊◊◊◊" },
  { set: "A2", number: 50, name: "Manaphy", type: "W Basic", rarity: "◊◊" },
  { set: "A2", number: 51, name: "Magnemite", type: "L Basic", rarity: "◊" },
  { set: "A2", number: 52, name: "Magneton", type: "L Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 53,
    name: "Magnezone",
    type: "L Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 54, name: "Voltorb", type: "L Basic", rarity: "◊" },
  { set: "A2", number: 55, name: "Electrode", type: "L Stage 1", rarity: "◊◊" },
  { set: "A2", number: 56, name: "Electabuzz", type: "L Basic", rarity: "◊" },
  {
    set: "A2",
    number: 57,
    name: "Electivire",
    type: "L Stage 1",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 58, name: "Shinx", type: "L Basic", rarity: "◊" },
  { set: "A2", number: 59, name: "Luxio", type: "L Stage 1", rarity: "◊◊" },
  { set: "A2", number: 60, name: "Luxray", type: "L Stage 2", rarity: "◊◊◊" },
  {
    set: "A2",
    number: 61,
    name: "Pachirisu ex",
    type: "L Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 62, name: "Rotom", type: "L Basic", rarity: "◊" },
  { set: "A2", number: 63, name: "Togepi", type: "P Basic", rarity: "◊" },
  { set: "A2", number: 64, name: "Togetic", type: "P Stage 1", rarity: "◊◊" },
  { set: "A2", number: 65, name: "Togekiss", type: "P Stage 2", rarity: "◊◊◊" },
  { set: "A2", number: 66, name: "Misdreavus", type: "P Basic", rarity: "◊" },
  {
    set: "A2",
    number: 67,
    name: "Mismagius ex",
    type: "P Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 68, name: "Ralts", type: "P Basic", rarity: "◊" },
  { set: "A2", number: 69, name: "Kirlia", type: "P Stage 1", rarity: "◊" },
  { set: "A2", number: 70, name: "Duskull", type: "P Basic", rarity: "◊" },
  { set: "A2", number: 71, name: "Dusclops", type: "P Stage 1", rarity: "◊◊" },
  { set: "A2", number: 72, name: "Dusknoir", type: "P Stage 2", rarity: "◊◊◊" },
  { set: "A2", number: 73, name: "Drifloon", type: "P Basic", rarity: "◊" },
  { set: "A2", number: 74, name: "Drifblim", type: "P Stage 1", rarity: "◊◊" },
  { set: "A2", number: 75, name: "Uxie", type: "P Basic", rarity: "◊◊" },
  { set: "A2", number: 76, name: "Mesprit", type: "P Basic", rarity: "◊◊◊" },
  { set: "A2", number: 77, name: "Azelf", type: "P Basic", rarity: "◊◊" },
  { set: "A2", number: 78, name: "Giratina", type: "P Basic", rarity: "◊◊◊" },
  { set: "A2", number: 79, name: "Cresselia", type: "P Basic", rarity: "◊◊◊" },
  { set: "A2", number: 80, name: "Rhyhorn", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 81, name: "Rhydon", type: "F Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 82,
    name: "Rhyperior",
    type: "F Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 83, name: "Gligar", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 84, name: "Gliscor", type: "F Stage 1", rarity: "◊◊" },
  { set: "A2", number: 85, name: "Hitmontop", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 86, name: "Nosepass", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 87, name: "Regirock", type: "F Basic", rarity: "◊◊" },
  { set: "A2", number: 88, name: "Cranidos", type: "F Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 89,
    name: "Rampardos",
    type: "F Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 90, name: "Wormadam", type: "F Stage 1", rarity: "◊" },
  { set: "A2", number: 91, name: "Riolu", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 92, name: "Lucario", type: "F Stage 1", rarity: "◊◊◊" },
  { set: "A2", number: 93, name: "Hippopotas", type: "F Basic", rarity: "◊" },
  { set: "A2", number: 94, name: "Hippowdon", type: "F Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 95,
    name: "Gallade ex",
    type: "F Stage 2",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 96, name: "Murkrow", type: "D Basic", rarity: "◊" },
  { set: "A2", number: 97, name: "Honchkrow", type: "D Stage 1", rarity: "◊◊" },
  { set: "A2", number: 98, name: "Sneasel", type: "D Basic", rarity: "◊" },
  {
    set: "A2",
    number: 99,
    name: "Weavile ex",
    type: "D Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 100, name: "Poochyena", type: "D Basic", rarity: "◊" },
  {
    set: "A2",
    number: 101,
    name: "Mightyena",
    type: "D Stage 1",
    rarity: "◊◊",
  },
  { set: "A2", number: 102, name: "Stunky", type: "D Basic", rarity: "◊" },
  { set: "A2", number: 103, name: "Skuntank", type: "D Stage 1", rarity: "◊◊" },
  { set: "A2", number: 104, name: "Spiritomb", type: "D Basic", rarity: "◊◊" },
  { set: "A2", number: 105, name: "Skorupi", type: "D Basic", rarity: "◊" },
  { set: "A2", number: 106, name: "Drapion", type: "D Stage 1", rarity: "◊◊" },
  { set: "A2", number: 107, name: "Croagunk", type: "D Basic", rarity: "◊" },
  {
    set: "A2",
    number: 108,
    name: "Toxicroak",
    type: "D Stage 1",
    rarity: "◊◊",
  },
  { set: "A2", number: 109, name: "Darkrai", type: "D Basic", rarity: "◊◊◊" },
  {
    set: "A2",
    number: 110,
    name: "Darkrai ex",
    type: "D Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 111, name: "Skarmory", type: "M Basic", rarity: "◊◊" },
  { set: "A2", number: 112, name: "Registeel", type: "M Basic", rarity: "◊◊" },
  { set: "A2", number: 113, name: "Shieldon", type: "M Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 114,
    name: "Bastiodon",
    type: "M Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 115, name: "Wormadam", type: "M Stage 1", rarity: "◊" },
  { set: "A2", number: 116, name: "Bronzor", type: "M Basic", rarity: "◊" },
  { set: "A2", number: 117, name: "Bronzong", type: "M Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 118,
    name: "Probopass",
    type: "M Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2",
    number: 119,
    name: "Dialga ex",
    type: "M Basic",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 120, name: "Heatran", type: "M Basic", rarity: "◊◊◊" },
  { set: "A2", number: 121, name: "Gible", type: "N Basic", rarity: "◊" },
  { set: "A2", number: 122, name: "Gabite", type: "N Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 123,
    name: "Garchomp",
    type: "N Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 124, name: "Lickitung", type: "C Basic", rarity: "◊" },
  {
    set: "A2",
    number: 125,
    name: "Lickilicky ex",
    type: "C Stage 1",
    rarity: "◊◊◊◊",
  },
  { set: "A2", number: 126, name: "Eevee", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 127, name: "Porygon", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 128, name: "Porygon2", type: "C Stage 1", rarity: "◊◊" },
  {
    set: "A2",
    number: 129,
    name: "Porygon-Z",
    type: "C Stage 2",
    rarity: "◊◊◊",
  },
  { set: "A2", number: 130, name: "Aipom", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 131, name: "Ambipom", type: "C Stage 1", rarity: "◊" },
  { set: "A2", number: 132, name: "Starly", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 133, name: "Staravia", type: "C Stage 1", rarity: "◊" },
  {
    set: "A2",
    number: 134,
    name: "Staraptor",
    type: "C Stage 2",
    rarity: "◊◊",
  },
  { set: "A2", number: 135, name: "Bidoof", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 136, name: "Bibarel", type: "C Stage 1", rarity: "◊" },
  { set: "A2", number: 137, name: "Buneary", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 138, name: "Lopunny", type: "C Stage 1", rarity: "◊" },
  { set: "A2", number: 139, name: "Glameow", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 140, name: "Purugly", type: "C Stage 1", rarity: "◊◊" },
  { set: "A2", number: 141, name: "Chatot", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 142, name: "Fan Rotom", type: "C Basic", rarity: "◊" },
  { set: "A2", number: 143, name: "Regigigas", type: "C Basic", rarity: "◊◊◊" },
  { set: "A2", number: 144, name: "Skull Fossil", type: "Item", rarity: "◊" },
  { set: "A2", number: 145, name: "Armor Fossil", type: "Item", rarity: "◊" },
  {
    set: "A2",
    number: 146,
    name: "Pokémon Communication",
    type: "Item",
    rarity: "◊◊",
  },
  { set: "A2", number: 147, name: "Giant Cape", type: "Tool", rarity: "◊◊" },
  { set: "A2", number: 148, name: "Rocky Helmet", type: "Tool", rarity: "◊◊" },
  { set: "A2", number: 149, name: "Lum Berry", type: "Tool", rarity: "◊◊" },
  { set: "A2", number: 150, name: "Cyrus", type: "Supporter", rarity: "◊◊" },
  {
    set: "A2",
    number: 151,
    name: "Team Galactic Grunt",
    type: "Supporter",
    rarity: "◊◊",
  },
  { set: "A2", number: 152, name: "Cynthia", type: "Supporter", rarity: "◊◊" },
  { set: "A2", number: 153, name: "Volkner", type: "Supporter", rarity: "◊◊" },
  { set: "A2", number: 154, name: "Dawn", type: "Supporter", rarity: "◊◊" },
  { set: "A2", number: 155, name: "Mars", type: "Supporter", rarity: "◊◊" },
  { set: "A2", number: 156, name: "Tangrowth", type: "G Stage 1", rarity: "☆" },
  { set: "A2", number: 157, name: "Combee", type: "G Basic", rarity: "☆" },
  { set: "A2", number: 158, name: "Carnivine", type: "G Basic", rarity: "☆" },
  { set: "A2", number: 159, name: "Shaymin", type: "G Basic", rarity: "☆" },
  { set: "A2", number: 160, name: "Mamoswine", type: "W Stage 2", rarity: "☆" },
  { set: "A2", number: 161, name: "Gastrodon", type: "W Stage 1", rarity: "☆" },
  { set: "A2", number: 162, name: "Manaphy", type: "W Basic", rarity: "☆" },
  { set: "A2", number: 163, name: "Shinx", type: "L Basic", rarity: "☆" },
  { set: "A2", number: 164, name: "Rotom", type: "L Basic", rarity: "☆" },
  { set: "A2", number: 165, name: "Drifloon", type: "P Basic", rarity: "☆" },
  { set: "A2", number: 166, name: "Mesprit", type: "P Basic", rarity: "☆" },
  { set: "A2", number: 167, name: "Giratina", type: "P Basic", rarity: "☆" },
  { set: "A2", number: 168, name: "Cresselia", type: "P Basic", rarity: "☆" },
  { set: "A2", number: 169, name: "Rhyperior", type: "F Stage 2", rarity: "☆" },
  { set: "A2", number: 170, name: "Lucario", type: "F Stage 1", rarity: "☆" },
  { set: "A2", number: 171, name: "Hippopotas", type: "F Basic", rarity: "☆" },
  { set: "A2", number: 172, name: "Spiritomb", type: "D Basic", rarity: "☆" },
  { set: "A2", number: 173, name: "Croagunk", type: "D Basic", rarity: "☆" },
  { set: "A2", number: 174, name: "Heatran", type: "M Basic", rarity: "☆" },
  { set: "A2", number: 175, name: "Garchomp", type: "N Stage 2", rarity: "☆" },
  { set: "A2", number: 176, name: "Staraptor", type: "C Stage 2", rarity: "☆" },
  { set: "A2", number: 177, name: "Bidoof", type: "C Basic", rarity: "☆" },
  { set: "A2", number: 178, name: "Glameow", type: "C Basic", rarity: "☆" },
  { set: "A2", number: 179, name: "Regigigas", type: "C Basic", rarity: "☆" },
  {
    set: "A2",
    number: 180,
    name: "Yanmega ex",
    type: "G Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 181,
    name: "Infernape ex",
    type: "R Stage 2",
    rarity: "☆☆",
  },
  { set: "A2", number: 182, name: "Palkia ex", type: "W Basic", rarity: "☆☆" },
  {
    set: "A2",
    number: 183,
    name: "Pachirisu ex",
    type: "L Basic",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 184,
    name: "Mismagius ex",
    type: "P Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 185,
    name: "Gallade ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 186,
    name: "Weavile ex",
    type: "D Stage 1",
    rarity: "☆☆",
  },
  { set: "A2", number: 187, name: "Darkrai ex", type: "D Basic", rarity: "☆☆" },
  { set: "A2", number: 188, name: "Dialga ex", type: "M Basic", rarity: "☆☆" },
  {
    set: "A2",
    number: 189,
    name: "Lickilicky ex",
    type: "C Stage 1",
    rarity: "☆☆",
  },
  { set: "A2", number: 190, name: "Cyrus", type: "Supporter", rarity: "☆☆" },
  {
    set: "A2",
    number: 191,
    name: "Team Galactic Grunt",
    type: "Supporter",
    rarity: "☆☆",
  },
  { set: "A2", number: 192, name: "Cynthia", type: "Supporter", rarity: "☆☆" },
  { set: "A2", number: 193, name: "Volkner", type: "Supporter", rarity: "☆☆" },
  { set: "A2", number: 194, name: "Dawn", type: "Supporter", rarity: "☆☆" },
  { set: "A2", number: 195, name: "Mars", type: "Supporter", rarity: "☆☆" },
  {
    set: "A2",
    number: 196,
    name: "Yanmega ex",
    type: "G Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 197,
    name: "Infernape ex",
    type: "R Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 198,
    name: "Pachirisu ex",
    type: "L Basic",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 199,
    name: "Mismagius ex",
    type: "P Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 200,
    name: "Gallade ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A2",
    number: 201,
    name: "Weavile ex",
    type: "D Stage 1",
    rarity: "☆☆",
  },
  { set: "A2", number: 202, name: "Darkrai ex", type: "D Basic", rarity: "☆☆" },
  {
    set: "A2",
    number: 203,
    name: "Lickilicky ex",
    type: "C Stage 1",
    rarity: "☆☆",
  },
  { set: "A2", number: 204, name: "Palkia ex", type: "W Basic", rarity: "☆☆☆" },
  { set: "A2", number: 205, name: "Dialga ex", type: "M Basic", rarity: "☆☆☆" },
  {
    set: "A2",
    number: 206,
    name: "Palkia ex",
    type: "W Basic",
    rarity: "Crown Rare",
  },
  {
    set: "A2",
    number: 207,
    name: "Dialga ex",
    type: "M Basic",
    rarity: "Crown Rare",
  },
  {
    set: "A2a",
    number: 1,
    name: "Heracross",
    type: "G Basic",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 2,
    name: "Burmy",
    type: "G Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 3,
    name: "Mothim",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 4,
    name: "Combee",
    type: "G Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 5,
    name: "Vespiquen",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 6,
    name: "Cherubi",
    type: "G Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 7,
    name: "Cherrim",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 8,
    name: "Cherrim",
    type: "G Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 9,
    name: "Carnivine",
    type: "G Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 10,
    name: "Leafeon ex",
    type: "G Stage 1",
    rarity: "◊◊◊◊",
  },
  {
    set: "A2a",
    number: 11,
    name: "Houndour",
    type: "R Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 12,
    name: "Houndoom",
    type: "R Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 13,
    name: "Heatran",
    type: "R Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 14,
    name: "Marill",
    type: "W Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 15,
    name: "Azumarill",
    type: "W Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 16,
    name: "Barboach",
    type: "W Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 17,
    name: "Whiscash",
    type: "W Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 18,
    name: "Snorunt",
    type: "W Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 19,
    name: "Froslass",
    type: "W Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 20,
    name: "Snover",
    type: "W Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 21,
    name: "Abomasnow",
    type: "W Stage 1",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 22,
    name: "Glaceon ex",
    type: "W Stage 1",
    rarity: "◊◊◊◊",
  },
  {
    set: "A2a",
    number: 23,
    name: "Origin Forme Palkia",
    type: "W Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 24,
    name: "Phione",
    type: "W Basic",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 25,
    name: "Pikachu",
    type: "L Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 26,
    name: "Raichu",
    type: "L Stage 1",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 27,
    name: "Electrike",
    type: "L Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 28,
    name: "Manectric",
    type: "L Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 29,
    name: "Clefairy",
    type: "P Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 30,
    name: "Clefable",
    type: "P Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 31,
    name: "Gastly",
    type: "P Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 32,
    name: "Haunter",
    type: "P Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 33,
    name: "Gengar",
    type: "P Stage 2",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 34,
    name: "Unown",
    type: "P Basic",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 35,
    name: "Rotom",
    type: "P Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 36,
    name: "Sudowoodo",
    type: "F Basic",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 37,
    name: "Phanpy",
    type: "F Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 38,
    name: "Donphan",
    type: "F Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 39,
    name: "Larvitar",
    type: "F Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 40,
    name: "Pupitar",
    type: "F Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 41,
    name: "Tyranitar",
    type: "F Stage 2",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 42,
    name: "Nosepass",
    type: "F Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 43,
    name: "Meditite",
    type: "F Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 44,
    name: "Medicham",
    type: "F Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 45,
    name: "Gible",
    type: "F Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 46,
    name: "Gabite",
    type: "F Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 47,
    name: "Garchomp ex",
    type: "F Stage 2",
    rarity: "◊◊◊◊",
  },
  {
    set: "A2a",
    number: 48,
    name: "Zubat",
    type: "D Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 49,
    name: "Golbat",
    type: "D Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 50,
    name: "Crobat",
    type: "D Stage 2",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 51,
    name: "Croagunk",
    type: "D Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 52,
    name: "Toxicroak",
    type: "D Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 53,
    name: "Magnemite",
    type: "M Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 54,
    name: "Magneton",
    type: "M Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 55,
    name: "Magnezone",
    type: "M Stage 2",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 56,
    name: "Mawile",
    type: "M Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 57,
    name: "Probopass ex",
    type: "M Stage 1",
    rarity: "◊◊◊◊",
  },
  {
    set: "A2a",
    number: 58,
    name: "Bronzor",
    type: "M Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 59,
    name: "Bronzong",
    type: "M Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 60,
    name: "Origin Forme Dialga",
    type: "M Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 61,
    name: "Giratina",
    type: "N Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 62,
    name: "Eevee",
    type: "C Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 63,
    name: "Snorlax",
    type: "C Basic",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 64,
    name: "Hoothoot",
    type: "C Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 65,
    name: "Noctowl",
    type: "C Stage 1",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 66,
    name: "Starly",
    type: "C Basic",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 67,
    name: "Staravia",
    type: "C Stage 1",
    rarity: "◊",
  },
  {
    set: "A2a",
    number: 68,
    name: "Staraptor",
    type: "C Stage 2",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 69,
    name: "Shaymin",
    type: "C Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 70,
    name: "Arceus",
    type: "C Basic",
    rarity: "◊◊◊",
  },
  {
    set: "A2a",
    number: 71,
    name: "Arceus ex",
    type: "C Basic",
    rarity: "◊◊◊◊",
  },
  {
    set: "A2a",
    number: 72,
    name: "Irida",
    type: "Supporter",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 73,
    name: "Celestic Town Elder",
    type: "Supporter",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 74,
    name: "Barry",
    type: "Supporter",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 75,
    name: "Adaman",
    type: "Supporter",
    rarity: "◊◊",
  },
  {
    set: "A2a",
    number: 76,
    name: "Houndoom",
    type: "R Stage 1",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 77,
    name: "Marill",
    type: "W Basic",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 78,
    name: "Unown",
    type: "P Basic",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 79,
    name: "Sudowoodo",
    type: "F Basic",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 80,
    name: "Magnemite",
    type: "M Basic",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 81,
    name: "Shaymin",
    type: "C Basic",
    rarity: "☆",
  },
  {
    set: "A2a",
    number: 82,
    name: "Leafeon ex",
    type: "G Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 83,
    name: "Glaceon ex",
    type: "W Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 84,
    name: "Garchomp ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 85,
    name: "Probopass ex",
    type: "M Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 86,
    name: "Arceus ex",
    type: "C Basic",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 87,
    name: "Irida",
    type: "Supporter",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 88,
    name: "Celestic Town Elder",
    type: "Supporter",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 89,
    name: "Barry",
    type: "Supporter",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 90,
    name: "Adaman",
    type: "Supporter",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 91,
    name: "Leafeon ex",
    type: "G Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 92,
    name: "Glaceon ex",
    type: "W Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 93,
    name: "Garchomp ex",
    type: "F Stage 2",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 94,
    name: "Probopass ex",
    type: "M Stage 1",
    rarity: "☆☆",
  },
  {
    set: "A2a",
    number: 95,
    name: "Arceus ex",
    type: "C Basic",
    rarity: "☆☆☆",
  },
  {
    set: "A2a",
    number: 96,
    name: "Arceus ex",
    type: "C Basic",
    rarity: "👑",
  },
  { set: "P-A", number: 1, name: "Potion", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 2, name: "X Speed", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 3, name: "Hand Scope", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 4, name: "Pokédex", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 5, name: "Poké Ball", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 6, name: "Red Card", type: "Item", rarity: "Promo" },
  {
    set: "P-A",
    number: 7,
    name: "Professor's Research",
    type: "Supporter",
    rarity: "Promo",
  },
  { set: "P-A", number: 8, name: "Pokédex", type: "Item", rarity: "Promo" },
  { set: "P-A", number: 9, name: "Pikachu", type: "L Basic", rarity: "Promo" },
  { set: "P-A", number: 10, name: "Mewtwo", type: "P Basic", rarity: "Promo" },
  { set: "P-A", number: 11, name: "Chansey", type: "C Basic", rarity: "Promo" },
  { set: "P-A", number: 12, name: "Meowth", type: "C Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 13,
    name: "Butterfree",
    type: "G Stage 2",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 14,
    name: "Lapras ex",
    type: "W Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 15, name: "Pikachu", type: "L Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 16,
    name: "Clefairy",
    type: "P Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 17, name: "Mankey", type: "F Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 18,
    name: "Venusaur",
    type: "G Stage 2",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 19,
    name: "Greninja",
    type: "W Stage 2",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 20,
    name: "Haunter",
    type: "P Stage 1",
    rarity: "Promo",
  },
  { set: "P-A", number: 21, name: "Onix", type: "F Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 22,
    name: "Jigglypuff",
    type: "C Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 23,
    name: "Bulbasaur",
    type: "G Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 24,
    name: "Magnemite",
    type: "L Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 25,
    name: "Moltres ex",
    type: "R Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 26, name: "Pikachu", type: "L Basic", rarity: "Promo" },
  { set: "P-A", number: 27, name: "Snivy", type: "G Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 28,
    name: "Volcarona",
    type: "R Stage 1",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 29,
    name: "Blastoise",
    type: "W Stage 2",
    rarity: "Promo",
  },
  { set: "P-A", number: 30, name: "Eevee", type: "C Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 31,
    name: "Cinccino",
    type: "C Stage 1",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 32,
    name: "Charmander",
    type: "R Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 33,
    name: "Squirtle",
    type: "W Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 34, name: "Piplup", type: "W Basic", rarity: "Promo" },
  { set: "P-A", number: 35, name: "Turtwig", type: "G Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 36,
    name: "Electivire",
    type: "L Stage 1",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 37,
    name: "Cresselia ex",
    type: "P Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 38,
    name: "Misdreavus",
    type: "P Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 39,
    name: "Skarmory",
    type: "M Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 40,
    name: "Chimchar",
    type: "R Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 41, name: "Togepi", type: "P Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 42,
    name: "Darkrai ex",
    type: "D Basic",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 43,
    name: "Cherrim",
    type: "G Stage 1",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 44,
    name: "Raichu",
    type: "L Stage 1",
    rarity: "Promo",
  },
  {
    set: "P-A",
    number: 45,
    name: "Nosepass",
    type: "F Basic",
    rarity: "Promo",
  },
  { set: "P-A", number: 46, name: "Gible", type: "F Basic", rarity: "Promo" },
  {
    set: "P-A",
    number: 47,
    name: "Staraptor",
    type: "C Stage 2",
    rarity: "Promo",
  },
  { set: "P-A", number: 48, name: "Manaphy", type: "W Basic", rarity: "Promo" },
  { set: "P-A", number: 49, name: "Snorlax", type: "C Basic", rarity: "Promo" },
];
